### ISSUE TITLE
[PE-D][Tester E] pay command after find causes card to disappear

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S1-CS2103T-T13-2/tp#180]
When Alex owes 95 in this case, inputting a find command causes Alex to disappear.

![image.png](https://raw.githubusercontent.com/quzhetao01/ped/main/files/aec00e44-a32b-401d-980c-c11dcafa65b5.png)

![image.png](https://raw.githubusercontent.com/quzhetao01/ped/main/files/1ad9cfb2-7f44-4ca1-91fd-df7e436233ea.png)

-------------
Labels: `type.FunctionalityBug` `severity.High`
original: quzhetao01/ped#6

**Comment by kokrui** [comment]
I'm not sure what's going on here but it looks pretty scary and I'd like to fix it, so I've asked the reporter here https://github.com/quzhetao01/ped/issues/6#issuecomment-1793903088

**Comment by conradsoon** [comment]
@kokrui similar behaviour replicated but possibly not a bug

`find bal/20` finds people whose balances are above $20.00.
Running `pay/owe` accordingly to cause their balance to drop below $20.00 causes their card to disappear (because it doesn't hit the criterion of balances being above $20.00 anymore. But arguably this is expected behaviour.

Unsure why this is the case actually, I thought it shouldn't affect LastShownList.

Good catch regardless @quzhetao01, thank you.

**Comment by quzhetao01** [comment]
Hi just a friendly tip! Maybe you might want to specify this behaviour into your UG so it won't confuse anyone. Hopefully you find this helpful!
